/*Queries that provide answers to the questions from all projects.*/


SELECT * FROM ANIMALS WHERE NAME LIKE '%mon';

SELECT NAME FROM ANIMALS WHERE DATE_OF_BIRTH BETWEEN '2016-01-01' AND '2019-12-01';

SELECT NAME FROM ANIMALS WHERE NEUTERED = true and ESCAPE_ATTEMPTS < 3;

SELECT DATE_OF_BIRTH FROM ANIMALS WHERE NAME IN ('Agumon','Pikachu');

SELECT NAME,ESCAPE_ATTEMPTS FROM ANIMALS WHERE WEIGHT_KG > 10.5;

SELECT * FROM ANIMALS WHERE NEUTERED = true

SELECT * FROM ANIMALS WHERE NAME <>  'Gabumon';

SELECT * FROM ANIMALS WHERE WEIGHT_KG >= 10.4 AND WEIGHT_KG <= 17.3;




-- Day 2
SELECT COUNT(NAME) AS NUMBER_OF_ANIMALS FROM ANIMALS
SELECT COUNT(NAME) AS NUMBER_OF_ANIMALS FROM ANIMALS WHERE ESCAPE_ATTEMPTS <=0;
SELECT AVG(WEIGHT_KG) AS AVERAGE_WEIGHT  FROM ANIMALS;
SELECT NEUTERED ,  MAX(ESCAPE_ATTEMPTS) AS  ESCAPES  FROM ANIMALS  GROUP BY NEUTERED;
SELECT SPECIES, MIN(WEIGHT_KG), MAX(WEIGHT_KG) FROM ANIMALS GROUP BY SPECIES;
SELECT SPECIES, AVG(ESCAPE_ATTEMPTS) FROM ANIMALS WHERE  DATE_OF_BIRTH >= '01-01-1990' AND  DATE_OF_BIRTH <= '31-12-2000'  GROUP BY SPECIES;
